ladoA= float (input("Digite o ladoA do retangulo"))
ladoB= float (input("Digite o ladoB do retangulo"))
calcÁrea=(ladoA) * (ladoB)
print("O calculo da área do retangulo,é:" + str(calcÁrea))
calcPerimetro = (2*ladoA) + (2*ladoB)
print("O calculo do perímetro,é:" + str(calcPerimetro))